### ISSUE TITLE
No presenta modelo en publicación de documentación

### ISSUE THREAD

**Issue by joseluisvaleriano** [haxdai/BPMNModeler#42]
Cuando se realizó la publicación de la documentación se generó un error de un token inesperado, , ahora ya no muestra el modelo .
http://207.248.177.63:8080/es/documenter/Documentation/_rid/209/_mod/m_vdoc?idp=Identificacion_y_atraccion_de_Proyectos_Estrategicos

![image](https://cloud.githubusercontent.com/assets/7728261/9313277/c519c192-44e7-11e5-9c89-59e884713712.png)

**Comment by haxdai** [comment]
Se movieron los issues de documentación a JIRA
