### ISSUE TITLE
Cargar una imagen en la documentación

### ISSUE THREAD

**Issue by joseluisvaleriano** [haxdai/BPMNModeler#43]
Cuando se realiza la documentación de un proceso, en el cual contiene una imagen de contenido, al cargar el documento, se presenta un error y no muestra la imagen cargada, ni en la edición ni publicación.

**Comment by haxdai** [comment]
Este proyecto es sólo sobre modeler, no sobre documenter. Hay que mover estos issues a jira @joseluisvaleriano @anaGarciaS .

**Comment by haxdai** [comment]
Se movieron los issues de documentación a JIRA
