### ISSUE TITLE
No se puede conectar 2 pools

### ISSUE THREAD

**Issue by joseluisvaleriano** [haxdai/BPMNModeler#44]
En un modelo que se tienen 2 pools y estos tienen una interacción, al realizar la interacción entre pools no se puede conectar.
![image](https://cloud.githubusercontent.com/assets/7728261/9645976/034d03de-5195-11e5-8683-ac1f387dac4f.png)

**Comment by haxdai** [comment]
¿Qué tipo de interacción? Los flujos normales no pueden cruzar entre pools. Los flujos de mensaje deben cruzar entre pools y no se pueden conectar a una tarea que no es de envío o recepción de mensaje.
